// Generated by CoffeeScript 1.6.2
/*
BindIt - A jQuery plugin to bind events with delay
Copyright (c) 2013, Opteemo.
https://github.com/Opteemo/BindIt
*/


(function() {
  (function($) {
    $.fn.bindTempo = function(type, delay, fn) {
      var dfn, locked;

      locked = false;
      dfn = function(event) {
        var call, element;

        element = this;
        call = function() {
          locked = false;
          fn.call(element, event);
        };
        if (!locked) {
          window.setTimeout(call, delay);
          locked = true;
        }
      };
      $.each(this, function(index, value) {
        $(value).on(type, dfn);
      });
    };
    return $.fn.bindSolo = function(type, delay, fn) {
      var dfn, id;

      id = null;
      dfn = function(event) {
        var call, element;

        element = this;
        call = function() {
          return fn.call(element, event);
        };
        if (id) {
          window.clearTimeout(id);
        }
        id = window.setTimeout(call, delay);
      };
      $.each(this, function(index, value) {
        $(value).on(type, dfn);
      });
    };
  })(jQuery);

}).call(this);
