// Generated by CoffeeScript 1.6.2
(function() {
  var bind_solo, bind_tempo;

  bind_tempo = function(bindit) {
    var mx, my, update_position;

    mx = null;
    my = null;
    $('#bindtempo').unbind('mousemove');
    $('#bindtempo').mousemove(function(e) {
      mx = e.pageX - this.offsetLeft;
      my = e.pageY - this.offsetTop;
    });
    update_position = function(x, y, animate) {
      var css;

      if (animate == null) {
        animate = false;
      }
      css = {
        left: x,
        top: y
      };
      if (animate) {
        $('#bindtempo .round').animate(css, 400);
      } else {
        css.left += 'px';
        css.top += 'px';
        $('#bindtempo .round').css(css);
      }
    };
    if (!bindit) {
      $('#bindtempo').mousemove(function(e) {
        update_position(mx - 10, my - 10);
      });
    } else {
      $('#bindtempo').bindTempo('mousemove', 500, function(e) {
        update_position(mx - 10, my - 10, true);
      });
    }
  };

  bind_solo = function(bindit) {
    var render;

    $('#bindsolo .input').unbind('keyup');
    render = function(text) {
      var c, html, key, _i, _len;

      html = '';
      for (_i = 0, _len = text.length; _i < _len; _i++) {
        c = text[_i];
        key = Math.floor((Math.random() * 10) + 1);
        html += '<span class="t' + key + '">' + c + '</span>';
      }
      $('#bindsolo .output').html(html);
    };
    if (!bindit) {
      $('#bindsolo .input').bind('keyup', function(e) {
        render($(this).val());
      });
    } else {
      $('#bindsolo .input').bindSolo('keyup', 500, function(e) {
        render($(this).val());
      });
    }
  };

  $(function() {
    return bind_tempo(false);
  });

  $(function() {
    return bind_solo(false);
  });

  $(function() {
    return $(':radio[name="bindtempo"]').change(function() {
      return bind_tempo($(this).val());
    });
  });

  $(function() {
    return $(':radio[name="bindsolo"]').change(function() {
      return bind_solo($(this).val());
    });
  });

}).call(this);
