// Generated by CoffeeScript 1.6.2
/*
BindIt - A jQuery plugin to bind events with delay
Copyright (c) 2013, Opteemo.
https://github.com/Opteemo/BindIt
*/


(function() {
  (function($) {
    $.fn.bindTempo = function(type, delay, fn) {
      var dfn, locked;

      locked = false;
      dfn = function() {
        var call;

        call = function() {
          locked = false;
          fn();
        };
        if (!locked) {
          window.setTimeout(call, delay);
          locked = true;
        }
      };
      $(this).bind(type, dfn);
    };
    return $.fn.bindSolo = function(type, delay, fn) {
      var dfn, id;

      id = null;
      dfn = function() {
        if (id) {
          window.clearTimeout(id);
        }
        id = window.setTimeout(fn, delay);
      };
      $(this).bind(type, dfn);
    };
  })(jQuery);

}).call(this);
